-- Create a new schema
create schema if not exists gifts;

-- Create a table to store gifts info
create table gifts.gifts_catalog(
	id serial primary key, 
	name varchar(255) not null,
	price decimal(10, 2) not null, -- decimal is a type of fixed-point data
	image_url text not null
);

create table gifts.gifts_received(
id uuid primary key default gen_random_uuid(),
donor_name varchar(255),
donor_message TEXT,
amount_paid decimal(10, 2) not null check (amount_paid >= 10),
mp_payment_id varchar(255) unique, -- id generated by Mercado Pago
status varchar(50) not null default 'PENDING',
	check (status in ('PENDING', 'PAID', 'CANCELED', 'REFUNDED', 'REJECTED', 'ACTION_REQUIRED', 'IN_PROCESS')),
created_at timestamp with time zone default current_timestamp,
paid_at timestamp with time zone default null
);

create table gifts.gifts_items_purchased (
id SERIAL primary key,
gift_received_id uuid not null references gifts.gifts_received(id) on delete cascade, -- all registers is gifts_received dependent
gift_id integer not null references gifts.gifts_catalog(id),
unit_price decimal(10, 2) not null,
quantity integer not null,
total_amount decimal(10, 2) not null, 
	constraint total_amount_calc check (total_amount = (unit_price * quantity))
);

-- We must use Index to optimize the data searches. This way aviods the "sequencial reading" 
create index idx_search_items_by_gifts_received_id on gifts.gifts_items_purchased(gift_received_id);