-- Create a new schema
create schema if not exists gifts;

-- Create a table to store gifts info
create table gifts.gifts_catalog(
	id serial primary key, 
	name varchar(255) not null,
	price decimal(10, 2) not null, -- decimal is a type of fixed-point data
	image_url text not null
);

create table gifts.gifts_received(
id uuid primary key default gen_random_uuid(),
external_reference varchar(255),
donor_name varchar(255),
donor_message TEXT,
gift_amount decimal(10, 2) not null check (gift_amount >= 10),
amount_paid decimal(10, 2),
net_received_amount decimal(10, 2),
fee_amount decimal(10, 2),
mp_payment_id varchar(255) unique, -- id generated by Mercado Pago
status varchar(50) not null default 'PENDING',
	check (status in ('PENDING', 'PAID', 'CANCELED', 'REFUNDED', 'REJECTED', 'ACTION_REQUIRED', 'IN_PROCESS')),
created_at timestamp with time zone default current_timestamp,
paid_at timestamp with time zone default null
);

create table gifts.gifts_items_purchased (
id SERIAL primary key,
gift_received_id uuid not null references gifts.gifts_received(id) on delete cascade, -- all registers is gifts_received dependent
gift_id integer not null references gifts.gifts_catalog(id),
unit_price decimal(10, 2) not null,
quantity integer not null,
total_amount decimal(10, 2) not null, 
	constraint total_amount_calc check (total_amount = (unit_price * quantity))
);

-- We must use Index to optimize the data searches. This way aviods the "sequencial reading" 
create index idx_search_items_by_gifts_received_id on gifts.gifts_items_purchased(gift_received_id);

create schema if not exists guests;

create table guests.guest_list (
	id serial primary key,
	full_name varchar(255) not null,
	phone varchar(11) unique,
	status varchar(20) not null default 'PENDING',
		check (status in ('PENDING', 'CONFIRMED', 'WILL_NOT_ATTEND')),
	guest_type varchar(20) not null,
		check (guest_type in ('GUEST', 'COMPANION')),
	date_of_birth date,
	guest_group varchar(10),
	invite_code varchar(20) unique,
	updated_at timestamp with time zone default now()
);

-- We must use Index to optimize the data searches. This way aviods the "sequencial reading"
create index idx_guest_group ON guests.guest_list(guest_group);
create index idx_guest_status ON guests.guest_list(status);

-- Function to generate invite code
create function guests.generate_invite_code()
returns varchar as $$
declare
    word text[] := array['LOVE', 'FOFO', 'FOFURA', 'MEL', 'ETERNO', 'CASA', 'GIFT', 'LINDO', 'AMOR', 'JANTAR', 'DANCA', 'ROCK', 'FOREVER', 'FESTA', 'PARTY', 'VERDADE', 'FRIEND', 'VINHO', 'APPLE', 'MUSICA', 'GAME', 'KISS', 'BEIJOS', 'CARINHO', 'QUITUTES', 'FAMILIA', 'FELICIDADE', 'SHOW', 'BENCAO', 'DEUS', 'CUIDADO', 'PAIXAO', 'ELEGANTE', 'BANQUETE', 'FILMES', 'SERIES', 'VIAGEM', 'LANCHE'];
    code text;
    already_exist boolean;
begin
    loop
        -- Random an word and concatenate to 3 random numbers
        code := word[floor(random() * array_length(word, 1) + 1)] || floor(random() * (999 - 100 + 1) + 100)::text;
        
        -- Ensures that generated code not exist in table
        select exists(select 1 from guests.guest_list where invite_code = code) INTO already_exist;
        
        -- If not exist, get out of the loop. If exist, it tries to generate another code.
        exit when not already_exist;
    end loop;
    
    return code;
end;
$$ language plpgsql;

-- Function to validate guest type and calls the trigger to generate invite code
create function guests.validation_invite_code_trigger()
returns trigger as $$
begin
	if new.guest_type = 'GUEST' then
		new.invite_code := guests.generate_invite_code();
	else
		new.invite_code := null;
	end if;
	return new;
end;
$$ language plpgsql;

-- Trigger to generate rsvp code
create trigger trg_generate_invite_code before insert on guests.guest_list for each row execute function guests.validation_invite_code_trigger();

-- Function to validate guest type and calls the trigger to delete guests from the same group
create function guests.validation_delete_on_cascade_group_trigger()
returns trigger as $$
begin
	-- Avoids infinite loop
	if pg_trigger_depth() > 1 then
		return old;
	end if;

	if old.guest_type = 'GUEST' then
		delete from guests.guest_list where guest_group = old.guest_group;
	end if;
	return old;
end;
$$ language plpgsql;

-- Trigger to delete guests from the same group
create trigger trg_delete_on_cascade_group after delete on guests.guest_list for each row execute function guests.validation_delete_on_cascade_group_trigger();
