spring.application.name=backend
server.port=8081
spring.output.ansi.enabled=always

# Obriga o Spring Boot a considerar o header de origem
server.forward-headers-strategy=framework

# Chave do CAPTCHA do Cloudflare
cloudflare.turnstile.secret-key=${CLOUDFLARE_CAPTCHA_SECRET_KEY}

# Autenticação Mercado Pago
mercadopago.access.token=${MP_ACCESS_TOKEN}
mercadopago.secret.signature=${MP_SECRET_SIGNATURE}

# Acesso ao banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/operation_wedding_db_homolog
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configuração do Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true