spring.application.name=backend
server.port=xxxx
spring.output.ansi.enabled=always

# Enable the DEBUG level specifically for your project package
logging.level.com.operationwedding=DEBUG

# View the SQL queries that Hibernate/JPA is running in the console
logging.level.org.hibernate.SQL=DEBUG
# View the actual parameter values being bound to the queries.
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# This variable stores the wedding date
operation-wedding.date=2026-10-18

# Forces Spring Boot to honor the origin header
server.forward-headers-strategy=framework

# Cloudflare's Captcha key
cloudflare.turnstile.secret-key=secretKeyFromCloudflare

# Mercado Pago authentication
mercadopago.access.token=MercadoPagoAcessToken
mercadopago.secret.signature=MercadoPagoSecretSignature

# Database access
spring.datasource.url=jdbc:postgresql://localhost:5432/databaseName
spring.datasource.username=databaseUsername
spring.datasource.password=databasePassword

# Colored console output
spring.output.ansi.enabled=ALWAYS

# Hibernate settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true