spring.application.name=backend
server.port=8082
spring.output.ansi.enabled=always

# Habilita o nível DEBUG especificamente no pacote do seu projeto
logging.level.com.operationwedding=DEBUG

# Ver as queries SQL que o Hibernate/JPA está executando no console:
logging.level.org.hibernate.SQL=DEBUG
# Ver os parâmetros reais (os valores) que estão entrando nas queries:
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Variável que guarda a data do casamento
operation-wedding.date=2026-10-18

# Obriga o Spring Boot a considerar o header de origem
server.forward-headers-strategy=framework

# Chave do CAPTCHA do Cloudflare
cloudflare.turnstile.secret-key=1x0000000000000000000000000000000AA

# Autenticação Mercado Pago
mercadopago.access.token=APP_USR-6792041632977686-011414-5b9258f61c146a4e43ad6eed93f8f21e-3134271904
mercadopago.secret.signature=f67665a2d234c02ae2524a83f390b52476ddca1f08c7cdab02eddd737875e214

# Acesso ao banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/operation_wedding_db_homolog
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Saídas coloridas no console
spring.output.ansi.enabled=ALWAYS

# Configuração do Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true